## Упражение 1

Создайте квадратный массив (размером больше 2), отсортируйте его столбцы, получите транспонированный массив (от отсортированного), объедините эти массивы вертикально, горизонтально и без оси (выведите на экран результат для каждого действия).

In [9]:
import numpy as np

data = np.array([[7, 31, 18], 
                 [84, 0, 2], 
                 [6, 91, 3]])

a1 = np.sort(data, axis=0)
a2 = a1.T
a3 = np.vstack((a1, a2))
a4 = np.hstack((a1, a2))
a5 = np.concatenate((a1, a2))

print('отсортированные столбцы: ', '\n', a1)
print('транспонированный массив: ', '\n', a2)
print('вертикальное объединение: ', '\n', a3)
print('горизонтальное объединение: ', '\n', a4)
print('ось 0: ', '\n', a5)

отсортированные столбцы:  
 [[ 6  0  2]
 [ 7 31  3]
 [84 91 18]]
транспонированный массив:  
 [[ 6  7 84]
 [ 0 31 91]
 [ 2  3 18]]
вертикальное объединение:  
 [[ 6  0  2]
 [ 7 31  3]
 [84 91 18]
 [ 6  7 84]
 [ 0 31 91]
 [ 2  3 18]]
горизонтальное объединение:  
 [[ 6  0  2  6  7 84]
 [ 7 31  3  0 31 91]
 [84 91 18  2  3 18]]
ось 0:  
 [[ 6  0  2]
 [ 7 31  3]
 [84 91 18]
 [ 6  7 84]
 [ 0 31 91]
 [ 2  3 18]]


## Упражнение 2

Напишите функцию, которая превращает список целых чисел (тип `list`) в `np.array`, занимающий наименьшую память, если известно, что данные, находящиеся в исходном списке - это:
- количество людей в каждом городе России;
- температура в градусах Цельсия, измеренная в разных хранилищах лаборатории (инкубатор для клеток млекопитающих, шкаф, холодильник, морозилка, кельвинатор -80℃)
- оценки 1 курса ФБМФ за письменный экзамен по матанализу.

In [8]:
import numpy as np;

# В списках данные хранятся в 64-битном виде

citizensList = [11920000, 4991000, 838321, 90485] #Москва, С-Петербург, Саратов, В. Луки
tempList = [-40, -79, -66, -80]                   #температура
gradeList = [2, 5, 6, 10]                         #оценки

citizensArray = np.array(citizensList, dtype=np.int32);  #преобразование списка в массив из 32 бит - max 4294967295
print(citizensArray)

tempArray = np.array(tempList, dtype=np.byte);     #преобразование списка в массив из 1 байта (8 бит)  -128 до 127   
print(tempArray)

gradeArray = np.array(gradeList, dtype=np.byte);   #преобразование списка в массив из 1 байта (8 бит)  -128 до 127
print(gradeArray)


[11920000  4991000   838321    90485]
[-40 -79 -66 -80]
[ 2  5  6 10]


## Упражнение 3

Прочитайте данные из файла `Cell_culture.txt` о количестве суспензионной культуры, заказанной сотрудниками и студентами лаборатории на определённые даты, в структурированный массив. Выведите на экран:
- суммарное количество культуры, заказанной на 5 апреля;
- имена студентов и сотрудников, которые заказали культуру на 9 апреля

In [11]:
import numpy as np;

#genfromtxt - загружает данные из текстового файла с указанием правил обработки
#delimiter='\t' - разделитель полей
#names=True использовать названия полей из файла : Date    Name    Volume    Comment
#dtype=['U8','U8','<i8','S10'] - формат данных U8 - Unicode, i8 - Integer, S10 - String
#контрольная распечатка массива данных:
#cellArray = np.genfromtxt('Cell_culture.txt', delimiter='\t', names=True, dtype=['U8','U8','<i8','S10'])
#print(cellArray)  

#Выбор столбца Volume всех значений от 5 апреля в столбце Date
vals = cellArray[cellArray["Date"] == "5-Apr"]["Volume"]
total = np.sum(vals)
print(vals, "  Cуммарное количество культуры = ", total)

#Имена студентов и сотрудников из столбца Name, которые заказали культуру на 9 апреля в столбце Date
names = cellArray[cellArray["Date"] == "9-Apr"]["Name"]
print("Имена студентов и сотрудников : ", names)

[  3  40 300]   Cуммарное количество культуры =  343
Имена студентов и сотрудников :  ['Dasha' 'Liza']
